name: CI Maven

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Checkout deepinthink/amoeba
        uses: actions/checkout@v4
        with:
          repository: deepinthink/amoeba
          path: deepinthink/amoeba

      - name: Build && Install amoeba-maven
        run: cd deepinthink/amoeba/tools/buildtools/java/amoeba-maven && ./mvnw install -B

      - name: Build && Install amoeba-external
        run: cd deepinthink/amoeba/infrastructure/external/java/amoeba-external && ./mvnw install -B

      - name: Build && Install amoeba-spring-boot
        run: cd deepinthink/amoeba/infrastructure/framework/java/amoeba-spring-boot && ./mvnw install -B

      - name: Build && Install carbon-spring-blockchain
        run: cd infrastructure/framework/java/carbon-spring-blockchain && ./mvnw install -B
